[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "manga"
path = "src/main.rs"

[dependencies]
manga = { path = "../manga", default-features = false, features = ["comici", "giga", "kadokomi"] }

anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
url = "2.5.3"
zip = "2.2.0"
image = "0.25.5"
tokio = "1.41.1"
