[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "manga"
path = "src/main.rs"

[dependencies]
manga = { path = "../manga", default-features = false, features = ["comici", "giga", "kadokomi"] }

anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
url = "2.5.8"
zip = "8.6.0"
image = "0.25.10"
tokio = "1.53.1"
