[package]
name = "manga"
version = "0.1.0"
edition = "2024"

[lib]
name = "manga"
path = "src/lib.rs"


[features]
default = ["giga", "kadokomi"]

giga = ["dep:feed-rs"]
kadokomi = ["dep:hex"]
fuz = ["dep:prost", "dep:prost-build", "dep:aes", "dep:hex", "dep:cbc", "dep:cipher"]
mangaz = []

[dependencies]
anyhow = "1.0.94"
image = "0.25.5"
reqwest = "0.12.9"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
futures = "0.3.31"
rayon = "1.10.0"
base64 = "0.22.1"
chrono = { version = "0.4.39", features = ["serde"] }
url = { version = "2.5.4", features = ["serde"] }
indicatif = { version = "0.17.9", features = ["futures", "rayon", "tokio"] }
zip = "2.2.1"
num_cpus = "1.16.0"
regex = "1.11.1"
scraper = "0.22.0"

# giga
feed-rs = { version = "2.3.0", optional = true }

# fuz
prost = { version = "0.13.4", optional = true }
aes = { version = "0.8.4", optional = true }
hex = { version = "0.4.3", optional = true }
cbc = { version = "0.1.2", optional = true }
cipher = { version = "0.4.4", features = ["block-padding"], optional = true }
thiserror = "2.0.8"

[build-dependencies]
prost-build = { version = "0.13.4", optional = true }
