[package]
name = "manga"
version = "0.1.0"
edition = "2024"

[lib]
name = "manga"
path = "src/lib.rs"


[features]
default = ["comici", "giga", "kadokomi"]

comici = []
giga = ["dep:feed-rs"]
kadokomi = ["dep:hex"]
fuz = ["dep:prost", "dep:prost-build", "dep:aes", "dep:hex", "dep:cbc", "dep:cipher"]
mangaz = []

[dependencies]
anyhow = "1.0.104"
image = "0.25.10"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
futures = "0.3.34"
base64 = "0.23.1"
chrono = { version = "0.4.45", features = ["serde"] }
url = { version = "2.5.8", features = ["serde"] }
indicatif = { version = "0.18.6", features = ["futures", "tokio"] }
zip = "8.6.0"
num_cpus = "1.17.0"
regex = "1.13.1"
scraper = "0.27.0"

# giga
feed-rs = { version = "2.4.0", optional = true }

# fuz
prost = { version = "0.14.4", optional = true }
aes = { version = "0.9.2", optional = true }
hex = { version = "0.4.3", optional = true }
cbc = { version = "0.2.1", optional = true }
cipher = { version = "0.5.2", features = ["block-padding"], optional = true }
thiserror = "2.0.20"

[build-dependencies]
prost-build = { version = "0.14.4", optional = true }
